name: Auto Commit

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        echo "GIT_USER_NAME=${{ secrets.GIT_USER_NAME }}" >> $GITHUB_ENV
        echo "GIT_USER_EMAIL=${{ secrets.GIT_USER_EMAIL }}" >> $GITHUB_ENV
        git config user.name "${{ secrets.GIT_USER_NAME }}"
        git config user.email "${{ secrets.GIT_USER_EMAIL }}"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Auto commit" || echo "No changes to commit"
        git push
