name: Auto Commit

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main  # Default branch सेट गर्नुहोस्

    - name: Set up Git
      run: |
        git config user.name "${{ secrets.GIT_USER_NAME }}"
        git config user.email "${{ secrets.GIT_USER_EMAIL }}"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Auto commit" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
