name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "apfsantosh@gmail.com"
        git config --global user.name "Syntu"

    - name: Push changes
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      run: |
        git add .
        git commit -m "Your commit message"
        git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/Syntu/Copy-Working.git
